### ISSUE TITLE
Wrong math on linux

### ISSUE THREAD

**Issue by binkiklou** [chirp-language/Chirp#10]
When writing constant math(where all the numbers are integer values and not variables) such as
in ``Test/constant_math.ch`` the produced assembly code will be blatantly wrong. As you can see in this output:

[wrong-output.txt](https://github.com/binkiklou/Chirp/files/3318602/wrong-output.txt)

Which is the compiled version of ``Test/constant_math.ch``, the code is wrong. This bug only occurs on Linux and doesn't happen on Windows(compiled with the latest version of Visual C++). This is very weird and I have absolutely no clue why it is happening.

Note: It is normal that no assembly code for the math is generated, this is an optimization trick made by the compiler because the result will always be the same.

**Comment by dithpri** [comment]
This seems to work for me, although I haven't looked much into the code (just checked that the rest of the test cases have the same output).
I don't think the original code *should* be working on Windows either, that's weird.
Anyway:
`Source/Compiler/Variable.cpp lines 262-267`
```diff
		if (t.Identifier == ARITHMETIC_OPERATOR_TOKEN)
		{
		//	std::cout<<std::to_string(std::stoi("100") / std::stoi("10"))<<std::endl;
			Source = Variable::Operation(i,env);
			SourceSet = true;
+			if(env->Syntax.at(i - 1).Identifier == INTERGER_TOKEN && env->Syntax.at(i + 1).Identifier == INTERGER_TOKEN)
+			{
+				break;
+			}
		}
```

**Comment by binkiklou** [comment]
My best bet is that vectors don't work the same way on windows and linux.
