### ISSUE TITLE
Motivation documentation

### ISSUE THREAD

**Issue by njayinthehouse** [chirp-language/Chirp#11]
## Describe your idea for a new feature
The title explains it perfectly

## Tell us why this would be beneficial to the project
There are plenty of low-level languages out there. What makes Chirp different? Are you focusing on certain features? Is it a project just for kicks? What's the central focus of this language?

## Additional stuff
Write anything here that wouldn't fit in the other categories.

**Comment by binkiklou** [comment]
I have litteraly no idea what this is.

**Comment by oSumAtrIX** [comment]
Chirp is small and portable, what makes it really cool to use. What it is missing is drawing capabilities and windows api support would be cool too outside the asm code

**Comment by binkiklou** [comment]
It's still missing critical features like conditions, but once the base is done. I'll try porting the windows api and some gnu libraries.
