### ISSUE TITLE
Object::Find methods

### ISSUE THREAD

**Issue by geekskick** [chirp-language/Chirp#17]
## Bug description
The `Object::Find*` methods have no way of telling if the object was found or not if the object is in position 0 of the vector.

## Where and when did it happen?
During testing.

## How to reproduce
```c++
TEST_CASE("Find by name without valid input"){
    const std::string target { "foo" };
    const std::vector<Object> list {
        { "fds", "rew", 0, 0, 0, 0, 0 },
        { "vxx", "wqa", 0, 0, 0, 0, 0 },
        { "gfd", "fds",0, 0, 0, 0, 0 }
    };
    const auto target_pos = Obj::FindByName(target, list);
    REQUIRE(0 == target_pos);
}
TEST_CASE("Find by name with match at start"){
    const std::string target { "foo" };
    const std::vector<Object> list {
        { target, "rew", 0, 0, 0, 0, 0 },
        { "vxx", "wqa", 0, 0, 0, 0, 0 },
        { "gfd", "fds",0, 0, 0, 0, 0 }
    };
    const auto target_pos = Obj::FindByName(target, list);
    REQUIRE(0 == target_pos);
}
```

## Proposal
Propose returning an iterator to the object's position in the vector, else `std::vector<Object>::end` if not found. Another approach might be to return `-1` on failure as that will never be an index in the vector.

**Comment by binkiklou** [comment]
I'll fix that when I'll be back from vacation
