### ISSUE TITLE
Variable::Register overwrites the 'int' type

### ISSUE THREAD

**Issue by geekskick** [chirp-language/Chirp#21]
## Bug description
When using the `Variable::Register` function with an object type of `"int"` or `"char"` this is overwritten by the `Type.compare("string")` clause. 

## Where and when did it happen?
During testing.

## How to reproduce
```c++
TEST_CASE("int object"){
    auto env = Environement();
    const auto t = Token{ VAR_DEC_TOKEN, "foo" };
    const auto t1 = Token { VAR_DEC_TOKEN, "int" };
    env.Syntax.push_back(t);
    env.Syntax.push_back(t1);
    env.Syntax.push_back(t);
    Variable::Register(0, &env);
    REQUIRE(env.ObjectList.size() == 1);
    REQUIRE(env.ObjectList[0].Name == "foo");
    REQUIRE(env.ObjectList[0].Size == 2);
}
```

## Proposed Fix
Add `== 0` after the `Type.compare("string")` test.

**Comment by binkiklou** [comment]
Every issue posted is painful because I'm in vacation right now and I can't fix it.

**Comment by geekskick** [comment]
I can stop creating them if you would like and do one mass fix? I am of the opinion is better to have them captured somewhere at least and then I can do one PR to address multiple issues. It’s your project though so please let me know best how to contribute. 

As a side note I’m enjoying learning about parsing and compiling etc from this project. Thanks for sharing it with the world.

**Comment by binkiklou** [comment]
You should really keep doing this, this is really helpful for me.
