### ISSUE TITLE
The compiler is being rewritten

### ISSUE THREAD

**Issue by binkiklou** [chirp-language/Chirp#32]
The old compiler was horrible, and it was really hard to work with, so I am rewritting it, and this time it will use fancy parsing algorithms and stuff like that.

**Comment by MonliH** [comment]
You should explain what type of "fancy parser" you are using. What else are you doing? Other than using a real parsing algorithm?

**Comment by binkiklou** [comment]
I'm also doing intermediate code generation

**Comment by MonliH** [comment]
Wow, big feature! Now I'm really curious. What do you mean intermediate code? And why do you need it? Why not compile directly to assembly? Can you give an example of what the intermediate code looks like?
