### ISSUE TITLE
Make the Command Line Interface more user friendly

### ISSUE THREAD

**Issue by binkiklou** [chirp-language/Chirp#9]
The command-line really isn't user-friendly. This need change, small changes like a help command or big changes like more specific commands could be really useful. Also, the build process really need more work.

**Comment by geekskick** [comment]
Are you ok with using boosts `program_options`, or do you prefer something like `getopt`?

**Comment by binkiklou** [comment]
We are trying to use the less amount of dependencies possible.

**Comment by geekskick** [comment]
Sure thing - I'd like to give this a crack now once the build system PRs are resolved if that's OK?

**Comment by geekskick** [comment]
I have been giving this a think and I reckon these are some options now that the build system is hot to trot:

- Implement just the 'help' command like requested in the same way you have
- Have a refactor or the existing code to make it more modular, possible using a table to configure it. This could be implemented in one of the following ways:
        1. [`getopt`](https://www.gnu.org/software/libc/manual/html_node/Getopt.html) - This isn't cross platform so you'd need to include the 'XGetopt' source for windows.
        2. [`TCLAP`](http://tclap.sourceforge.net) - External dependancy but should work on all platforms. Header only library.
        3. [`boost::program_options`](https://theboostcpplibraries.com/boost.program_options)- External dependancy should work on all platforms.
        4. Roll my own - no external deps but it won't be as fully tested as an existing solution 're-inventing the wheel'

I believe that the best approach would be to use `TCLAP`by including the source as a submodule, and then including the directory in the include path. Then the CLI parsing is more modular, using a table or something to configure it. 

Please let me know how you would like me continue.
